name: "Release"

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Install Nix
      uses: cachix/install-nix-action@v15
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          extra-substituters = file://${{ github.workspace }}/store-cache?trusted=true

    - name: Set up store cache
      uses: actions/cache@v2
      with:
        path: store-cache
        key: ghc921

    - name: Generate documentation
      run: nix build .#ghc921.doc -L

    - name: Prepare documentation
      run: cp -r ./result-doc/share/doc/*/html .

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: haddock
        path: html

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

  upload:
    name: Upload Documentation
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: haddock
        path: html

    - name: Upload
      if: success()
      uses: crazy-max/ghaction-github-pages@v2.6.0
      with:
        build_dir: html
        target_branch: docs
        keep_history: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
